services:
  mysql:
    image: mysql:9
    container_name: mysql9
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: wtf
      MYSQL_USER: wtf
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
  
  redis:
    image: redis:7
    container_name: redis7
    restart: always
    ports:
      - "6379:6379"