server:
  port: 8088
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wtf?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowMultiQueries=true
    username: wtf
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000