spring:
  application:
    name: wtf
  profiles:
    active: dev-office
logging:
  level:
    root: info
springdoc:
  api-docs:
    enabled: on
    path: /api-docs
  swagger-ui:
    enabled: on
    path: /swagger-ui.html
