spring:
  application:
    name: wtf
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
logging:
  level:
    root: info
springdoc:
  api-docs:
    enabled: on
    path: /api-docs
  swagger-ui:
    enabled: on
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
sql:
  mock:
    enable: ${MOCK:false}
  reset:
    enable: ${RESET:false}
    path: classpath:sql/reset-tables.sql
