spring:
  application:
    name: wtf
  profiles:
    active: dev-office
logging:
  level:
    root: info
springdoc:
  api-docs:
    enabled: true
    path: /docs/api
  swagger-ui:
    path: /docs/swagger-ui.html
